# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f66e7b3f9df74c95b118adc84622e411ed69082069ce0d5a6667f908cefd81a9a04e3a7283fcea5c2f88d3d6bd4d9de7e3f69e3b96032877194b781cffc308ba

test:
  secret_key_base: 53b6317f8373e19909836dce715386ee7b0717268673f9ef622c7ae0399554f9e14a325a3e7f3b0f00385782c3d040685b726aead704fd3ade395f3110302e12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
